# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\SfRegister\:
    resource: '../Classes/*'

  Evoweb\SfRegister\Property\TypeConverter\DateTimeConverter:
    tags:
      - name: extbase.type_converter
        priority: 2
        target: DateTime
        sources: integer, string, array

  Evoweb\SfRegister\Property\TypeConverter\FrontendUserConverter:
    tags:
      - name: extbase.type_converter
        priority: 31
        target: Evoweb\SfRegister\Domain\Model\FrontendUser
        sources: integer, string

  Evoweb\SfRegister\Property\TypeConverter\ObjectStorageConverter:
    tags:
      - name: extbase.type_converter
        priority: 21
        target: TYPO3\CMS\Extbase\Persistence\ObjectStorage
        sources: array

  Evoweb\SfRegister\Property\TypeConverter\UploadedFileReferenceConverter:
    tags:
      - name: extbase.type_converter
        priority: 31
        target: TYPO3\CMS\Extbase\Domain\Model\FileReference
        sources: array
